# server:
#   port: 8080

# spring:
#   datasource:
#     # url: jdbc:mysql://localhost:3306/ride_fast_db?createDatabaseIfNotExist=true
#     url: mysql://root:ThrAysfAxeIEJIHwMuiZVnzeyvlAmvmI@nozomi.proxy.rlwy.net:55551/railway
#     username: root
#     password: 80095
#     # url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.mpdtafocfwffptvrdruq&password=KzpsKLu8.@qpJgT

#   jpa:
#     hibernate:
#       ddl-auto: update
    
#     show-sql: true
#     properties:
#       format_sql: true


spring:
  datasource:
    url: jdbc:mysql://nozomi.proxy.rlwy.net:55551/railway
    username: root
    password: ThrAysfAxeIEJIHwMuiZVnzeyvlAmvmI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
